### ISSUE TITLE
Pod status still in ContainerCreating

### ISSUE THREAD

**Issue by Kelysa** [miciek/pacman-kubernetes-linkerd#1]
Hello,

I configured all of things like you but my pod are still in ContainerCreating and i don't know why

 $ kubectl get po,svc -n default
NAME        READY     STATUS                   RESTARTS   AGE
l5d-p52ln   0/2          ContainerCreating   4                 10h

$ kubectl describe pods
Failed create pod sandbox … error response from daemon : driver failled programming external Connectivity on Endpoint k8s … Error starting userland proxy: listen 0.0.0.0:4140 bind: adress already in use

Can you help me please ?
Thanks

**Comment by miciek** [comment]
hi @Kelysa. It means that the port `4140` is already taken on the node that `linkerd` is running. ssh into this machine and find out the process using `lsof`.
